#!/bin/bash
# opens chrome with a provided url
# if first argument is 'search', it performs a 
# chrome search with the keywords provided
#
# examples:
# chrome google.com
# chrome search why is blake so awesome?
# chrome -n apple.com
# chrome -n search why is parker so awesome?
# 
# notes:
# -n flag triggers new window

# globals
search_url='http://google.com/search?q='

# opens a new chrome window w/ or w/o search
function newChromeWindow {    
    osascript -e "tell application \"/Applications/Google Chrome.app\"" -e "make new window" -e "activate" -e "end tell"
}

# opens a new tab in a current chrome session w/ or w/o search
# otherwise, opens up google chrome w/ or w/o search
function googleChrome {
    if [[ "$1" == "search" ]]; then
        echo "searching..."
        searchlist=("$@")
        unset searchlist[0]
        IFS='+'
        open -a "/Applications/Google Chrome.app"  $search_url"${searchlist[*]}"
    else
        if [[ ! "$1" =~ "http://" ]] && [[ ! "$1" =~ "https://" ]]; then
            open -a "/Applications/Google Chrome.app" http://$1
        else
            open -a "/Applications/Google Chrome.app" $1
        fi
    fi
}

# function calls for user input
if [[ "$1" == "-n" ]]; then
    newChromeWindow "$@"
    shift
fi
googleChrome "$@"








