#!/bin/bash
# positions terminal window on right

if [ $(uname) == "Darwin" ]; then
	# setting position of current window
	osascript ~/.scripts/right.scpt
else
	# getting dimensions
	dimstr=`xrandr | tr ' ' '\n' | egrep '.*?x.*?\+0\+0' | head -1 | sed 's/+.*//g'`
	set -- "$dimstr"
	IFS="x"; declare -a dims=($*)
	width=`expr "${dims[0]}" / 2`
	offset=`expr $width + 5`
	height="${dims[1]}"
	wmctrl -r :ACTIVE: -e 0,$offset,0,$width,$height
fi