#!/bin/bash
# opens sublime with provided text file
#
# examples:
# sublime file.txt script.py

if [[ "$OSTYPE" =~ "linux" ]]; then
    /opt/sublime_text/sublime_text "$@"
else
    /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl "$@"
fi