#!/bin/bash
# opens sublime with provided text file
#
# examples:
# sublime file.txt script.py

if [ $(uname) == "Darwin" ]; then
    /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl "$@"
else
    /opt/sublime_text/sublime_text "$@"
fi